### ISSUE TITLE
Engineering Blog

### ISSUE THREAD

**Issue by TroyKomodo** [ScuffleTV/scuffle#108]
We should try setup a blog where we can write about some of the stuff with video / config / networking / cdn / other cool features we will end up building to support the live streaming platform.

**Comment by TroyKomodo** [comment]
@4w3Official has recommended https://ghost.org/ for this project I think it could be interesting to try it.

**Comment by 4w3Official** [comment]
The blog is up and running at [bytes.scuffle.tv](https://bytes.scuffle.tv)
Still a work in progress - a few things are still being tweaked

_Updates will be posted here_
