### ISSUE TITLE
[Feature]: refactor auth dialog

### ISSUE THREAD

**Issue by lennartkloock** [ScuffleTV/scuffle#132]
### Tell us about your Wish

The current auth dialog implementation is pretty bad.

### Participation

- [x] I am willing to submit a pull request to implement this

### Disclaimer

- [X] I agree

**Comment by TroyKomodo** [comment]
Perhaps have the ability to generate a password?

**Comment by TroyKomodo** [comment]
Also, maybe allow for a magic email login link. Which will send the user an email which when they click the link, bypasses the password authentication.

**Comment by lennartkloock** [comment]
> Also, maybe allow for a magic email login link. Which will send the user an email which when they click the link, bypasses the password authentication.

This issue is just for frontend refactoring because the code is kinda weird. But you could maybe open a separate issue for this.
