### ISSUE TITLE
scaffolding for projects

### ISSUE THREAD

**Issue by TroyKomodo** [ScuffleTV/scuffle#20]
Add initial scaffolding for projects

We have:
- backend/api (rust)
- video/ingest (rust)
- video/edge (rust)
- video/trancode (rust)
- frontend/website (rust)
- frontend/player (rust)

The scaffolding wont have any logic or code but will be a structure and layout and we can then ticket development for each of the projects.

**Comment by TroyKomodo** [comment]
linear wtf

**Comment by treuks** [comment]
NaNNaNundefined
