### ISSUE TITLE
Add CONTRIBUTING.md 

### ISSUE THREAD

**Issue by IS2511** [ScuffleTV/scuffle#3]
In a project this big having no commit message format could lead to diverse styles for messages which makes it harder to read and search the commit history. Also, since this is a monorepo, dividing it into components (scopes) and signifying what part of the repo the commit relates to in a unified way could be really helpful.
I propose the following git message conventions: https://karma-runner.github.io/6.4/dev/git-commit-msg.html

The only icky part is the `build` type, it's recent and in previous versions it was `chore`. Many automated up-keep solutions for code still use the `chore` type (ex: Renovate). But that is a minor inconvenience, these conventions are used by many developers and git bots.

**Comment by IS2511** [comment]
There are many variations on the basic semantic commit message conventions, such as versions supporting emoji: https://gist.github.com/alpteo/e93d754e5e09907c6362c4230fb66f87
Or versions that use only the emoji for types: https://gitmoji.dev/ (giant list btw)
GitMoji integration etc: https://dev.to/javidjms/git-write-better-commits-with-gitmoji-3193

**Comment by TroyKomodo** [comment]
Great question, so on draft PRs like #2 you can see that i have committed a bunch of commits with random names. Before I merge this PR I will squash all the commits into a single commit and then do a merge on master (not a squash merge)

So while we are developing a PR the commit names dont need to be anything special. Once we are ready to merge and we squash the commits into a single commit. We should in the commit title briefly mention what the commit does and then in the commit body we should reference the tickets from https://github.com/orgs/ScuffleTV/projects/1

For example when the first PR gets merged
it will look like

```
Added documentation and flow charts
#1 
```

Currently I am trying out using github projects. I dont know how good it is or if its actually useful if it isnt ill just switch to JIRA or some other project management tool.

**Comment by IS2511** [comment]
This all sounds like it needs to be documented in `CONTRIBUTION.md`, perhaps a  task for later.

Just want to mention, the `all` scope seems redundant, IMO it's much better to omit the parenthesis all together if the scope is too big or undecidable.

**Comment by TroyKomodo** [comment]
There is a script when making change logs which looks for `tag(scope)` syntax not sure if it works without the `scope` part. Which is why I put it there. And yeah that sounds good ill make a ticket for it and repurpose this issue.

**Comment by TroyKomodo** [comment]
Closed in favour of the ticked issue.

**Comment by treuks** [comment]
I suggest looking into [commitizen](https://commitizen-tools.github.io/commitizen/#:~:text=Commitizen%20is%20a%20tool%20designed,and%20enforces%20writing%20descriptive%20commits.)
