### ISSUE TITLE
Login/Register Page

### ISSUE THREAD

**Issue by TroyKomodo** [ScuffleTV/scuffle#36]
Need to create the page for signup and login
Should use some sort of reCAPTCHA system to try mitigate bot accounts.

for the password hashing algo, i have previously used argon2 and bcrypt, I believe argon2 was the best however I havent kept up with the state of password hashing.

**Comment by mmattbtw** [comment]
we should go passwordless

- users forget passwords
- users leak passwords
- service gets compromised, passwords leak
- if user's email gets compromised, thats their/their service's fault

**Comment by TroyKomodo** [comment]
I dont think going passwordless is best, I think having both is good. So like you can go passwordless if you have an email and we can send you a magic link?

Auth.js wont work since we are not using a javascript backend.

**Comment by TroyKomodo** [comment]
@treuks is it free?

**Comment by treuks** [comment]
ye

**Comment by IS2511** [comment]
> for the password hashing algo, i have previously used argon2 and bcrypt, I believe argon2 was the best however I havent kept up with the state of password hashing.

AFAIK "argon2 + salt + pepper" is the last word in password hashing. bcrypt is practically legacy by now. Giving it a quick search just[^1] in[^2] case[^3], I see no problems. I would encourage to read the OWASP cheatsheet[^1] in particular. 

If we really want to get into it, we could try to follow NIST guidelines[^4]. Document B says you *SHOULD* salt and lists a few recommended options for hashing:
> Examples of suitable key derivation functions include Password-based Key Derivation Function 2 (PBKDF2) [[SP 800-132]](https://pages.nist.gov/800-63-3/sp800-63b.html#SP800-132) and Balloon [[BALLOON]](https://pages.nist.gov/800-63-3/sp800-63b.html#balloon). A memory-hard function SHOULD be used because it increases the cost of an attack. The key derivation function SHALL use an approved one-way function such as Keyed Hash Message Authentication Code (HMAC) [[FIPS 198-1]](https://pages.nist.gov/800-63-3/sp800-63b.html#FIPS198-1), any approved hash function in [SP 800-107](https://pages.nist.gov/800-63-3/sp800-63b.html#SP800-107), Secure Hash Algorithm 3 (SHA-3) [[FIPS 202]](https://pages.nist.gov/800-63-3/sp800-63b.html#FIPS202), CMAC [[SP 800-38B]](https://pages.nist.gov/800-63-3/sp800-63b.html#SP800-38B) or Keccak Message Authentication Code (KMAC), Customizable SHAKE (cSHAKE), or ParallelHash [[SP 800-185]](https://pages.nist.gov/800-63-3/sp800-63b.html#SP800-185).

But if we don't need FIPS-140[^5] compliance, I don't think we need to strictly follow that.

[^1]: https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html ([archived 2023-03-03](https://web.archive.org/web/20230303090951/https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html))
[^2]: https://developer.okta.com/blog/2019/07/29/hashing-techniques-for-password-storage
[^3]: https://codesigningstore.com/what-is-the-best-hashing-algorithm ([archived 2023-03-03](https://web.archive.org/web/20230303093918/https://codesigningstore.com/what-is-the-best-hashing-algorithm))
[^4]: https://pages.nist.gov/800-63-3/
[^5]: https://en.wikipedia.org/wiki/FIPS_140
