### ISSUE TITLE
Basic User Settings

### ISSUE THREAD

**Issue by TroyKomodo** [ScuffleTV/scuffle#61]
## Profile

- [x] Custom chat color
- [ ] Profile Picture (Depends on #123)
- [x] Display name (capitalization of username)

## Account

- [x] Change password (#141)
- [x] Change email
- [x] 2FA settings (#125)

This issue doesn't contain more advanced settings like notification and billing settings.

**Comment by StarFang208** [comment]
Regardi personalizations, you limit certain options behind a paywall or no limits?

**Comment by TroyKomodo** [comment]
Not really @StarFang208
