### ISSUE TITLE
Build system for the monorepo

### ISSUE THREAD

**Issue by treuks** [ScuffleTV/scuffle#7]
We need to pick a build system for the monorepo.

**Comment by IS2511** [comment]
`Justfile` Clueless

**Comment by 4w3Official** [comment]
Best to use one of the following: [https://monorepo.tools/#tools-review](https://monorepo.tools/#tools-review)

**Comment by IS2511** [comment]
> https://monorepo.tools/#tools-review

Just read the feature lists.
Lage, Lerna, Rush and Turborepo self-eliminate by having no or poor support outside of NPM/JS. Bazel, Gradle, Nx or Pants are my candidates so far.
Out of the 4 candidates Bazel and Nx stand out by having more out of the box and relying less on custom plugins (ones we would need to write, like on Pants).
Nx is overall more covered in green checks of features, but Bazel is backed by Google so 🤷 .
Pants also seems viable but I've never heard of it before so I don't know about what backs it.
IMO Nx if we are feeling futuristic and next-gen, and Bazel if we are feeling a bit corporate and stable today. Both are good tools most probably.

**Comment by IS2511** [comment]
For Rust.
Nx: https://github.com/nxrs/cargo
Bazel: https://github.com/bazelbuild/rules_rust (http://bazelbuild.github.io/rules_rust/)
Gradle is very focused on Java ig and has no Rust support/plugin not related to Android (from what I could find with a 5 min search).
Pants is not focused on Rust, no good support, first class python though.

**Comment by TroyKomodo** [comment]
For now, i think we are just going to use cargo and github cache. We dont need one it seems but we can reopen this issue and restore the ticket if it does end up being something we should look into.
